# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8doXZ7OuO6XjYlcEgDi1t2R-r8UJ1uQ
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# --- 1. การเตรียมข้อมูลและเทรนโมเดล ---
# ใช้ @st.cache_data เพื่อไม่ให้แอปเทรนโมเดลใหม่ทุกครั้งที่ขยับปุ่ม
@st.cache_data
def train_model():
    # โหลดข้อมูลที่สร้างจากสคริปต์แรก
    df = pd.read_csv('customer_churn_mock.csv')
    X = df[['Age', 'Tenure_Months', 'Monthly_Charge', 'Support_Tickets']]
    y = df['Churn']

    # เทรนโมเดล
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model

model = train_model()

# --- 2. การออกแบบส่วนแสดงผล (UI) ---
st.set_page_config(page_title="Customer Churn Prediction", page_icon="📊")

st.title("📊 ระบบคาดการณ์ลูกค้ายกเลิกบริการ")
st.markdown("แอปพลิเคชันสำหรับทีมการตลาดเพื่อ **ประเมินความเสี่ยง** และ **จัดแคมเปญรักษาลูกค้า** เชิงรุก")
st.divider()

# --- 3. แถบเครื่องมือด้านข้าง (Sidebar) สำหรับกรอกข้อมูล ---
st.sidebar.header("📝 กรอกข้อมูลลูกค้าใหม่")

age = st.sidebar.slider("อายุ (ปี)", 18, 70, 35)
tenure = st.sidebar.slider("อายุการใช้งาน (เดือน)", 1, 72, 6)
charge = st.sidebar.number_input("ค่าบริการรายเดือน (บาท)", 500.0, 3000.0, 1500.0)
tickets = st.sidebar.selectbox("จำนวนครั้งที่ติดต่อ Support (ครั้ง)", [0, 1, 2, 3, 4, 5])

# --- 4. การทำนายผล (Prediction) ---
# จัดรูปแบบข้อมูลที่รับเข้ามาให้ตรงกับตอนเทรน
input_data = pd.DataFrame({
    'Age': [age],
    'Tenure_Months': [tenure],
    'Monthly_Charge': [charge],
    'Support_Tickets': [tickets]
})

# ให้โมเดลทำนาย
prediction = model.predict(input_data)[0]
probability = model.predict_proba(input_data)[0][1] # ดึงค่าความน่าจะเป็นที่จะเป็น 1 (Churn)

# --- 5. การแสดงผลลัพธ์เชิงธุรกิจ (Business Action) ---
st.subheader("💡 ผลการวิเคราะห์และข้อเสนอแนะทางธุรกิจ")

# กำหนดเงื่อนไขการแสดงผลตามผลลัพธ์ของโมเดล
if prediction == 1:
    st.error(f"⚠️ ความเสี่ยงสูง: ลูกค้ารายนี้มีโอกาสยกเลิกบริการ ({probability:.1%})")

    st.markdown("### 🎯 Action Plan แนะนำ:")
    st.info("""
    * **Retention Offer:** ส่ง SMS มอบคูปองส่วนลด 20% สำหรับรอบบิลถัดไป
    * **Proactive Service:** ให้ทีม Customer Success โทรสอบถามปัญหาการใช้งานโดยด่วน
    * **Expected ROI:** ค่าใช้จ่ายในการโทร+ส่วนลด (ประมาณ 400 บาท) คุ้มค่ากว่าการหาลูกค้าใหม่ (CAC ประมาณ 1,500 บาท)
    """)
else:
    st.success(f"✅ ปลอดภัย: ลูกค้ามีแนวโน้มใช้งานต่อ (ความเสี่ยงเพียง {probability:.1%})")

    st.markdown("### 🎯 Action Plan แนะนำ:")
    st.info("""
    * **Relationship Building:** ส่งอีเมลขอบคุณสำหรับการใช้งานอย่างต่อเนื่อง
    * **Cross-sell Opportunity:** เสนอแพ็กเกจเสริม (Add-on) ที่เข้ากับพฤติกรรมการใช้งาน
    """)