# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaVA9WHSEFy04RqAJxmT_6hW-t6IrpTm
"""

import pandas as pd
import numpy as np

# กำหนด Seed เพื่อให้สุ่มได้ค่าเดิมทุกครั้ง
np.random.seed(42)
n_samples = 1000

# 1. สร้าง Features (ข้อมูลพฤติกรรมลูกค้า)
data = {
    'CustomerID': range(1, n_samples + 1),
    'Age': np.random.randint(18, 70, n_samples),
    'Tenure_Months': np.random.randint(1, 72, n_samples), # อายุการใช้งาน
    'Monthly_Charge': np.random.uniform(500, 3000, n_samples).round(2), # ยอดบิล
    'Support_Tickets': np.random.randint(0, 6, n_samples) # การร้องเรียนปัญหา
}
df = pd.DataFrame(data)

# 2. สร้าง Target (Churn) โดยอิงจากพฤติกรรม
# สูตรจำลอง: โอกาส Churn จะเพิ่มขึ้นถ้าตั๋วร้องเรียนสูง, อายุการใช้งานน้อย และยอดบิลสูง
churn_prob = (
    (df['Support_Tickets'] * 0.12) +
    (1 / (df['Tenure_Months'] + 1)) * 0.4 +
    (df['Monthly_Charge'] / 3000) * 0.1
)

# แปลงความน่าจะเป็นให้เป็น 0 (ไม่ยกเลิก) หรือ 1 (ยกเลิก)
df['Churn'] = (np.random.rand(n_samples) < churn_prob).astype(int)

# บันทึกเป็นไฟล์ CSV
df.to_csv('customer_churn_mock.csv', index=False)
print("✅ สร้างไฟล์ customer_churn_mock.csv สำเร็จแล้ว! (จำนวน 1000 records)")